window.APP_CATALOG = [
  {
    id: "are-you-human",
    name: "Are You Human? Prove It",
    category: "Comedy puzzle game",
    description: "Survive suspicious CAPTCHA tests, strange human challenges, and a confidence meter that distrusts perfection.",
    icon: "/assets/icons/are-you-human.png",
    screenshot: "/assets/screenshots/are-you-human.png",
    screenshotAlt: "Are You Human home screen with a suspicious checkbox mascot and Prove It button",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "lime",
    platforms: [],
    actions: []
  },
  {
    id: "road-trip-arcade",
    name: "Road Trip Arcade",
    category: "Road trip games",
    description: "Turn miles into play with license-plate spotting, road bingo, trivia, word races, and shared trip scores.",
    icon: "/assets/icons/road-trip-arcade.webp",
    screenshot: "/assets/screenshots/road-trip-arcade.webp",
    screenshotAlt: "Road Trip Arcade pixel-art daytime highway home screen with five game choices",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "arcade",
    platforms: [],
    actions: []
  },
  {
    id: "calcspace",
    name: "CalcSpace",
    category: "Everyday utility",
    description: "Use one, two, or four calculators at once without clearing your work between calculations.",
    icon: "/assets/icons/calcspace.webp",
    screenshot: "/assets/screenshots/calcspace.webp",
    screenshotAlt: "CalcSpace showing two working calculators on an iPhone",
    status: "available",
    statusLabel: "Available now",
    accent: "indigo",
    platforms: [{ label: "iPhone & iPad", kind: "ios" }],
    actions: [
      { label: "View on the App Store", href: "https://apps.apple.com/us/app/calcspace/id6789995674", primary: true }
    ]
  },
  {
    id: "clay-scorecard",
    name: "Yawtzee: Best Scorecard",
    category: "Scorecard",
    description: "A cheerful, tactile score sheet for keeping real five-dice games moving with friends and family.",
    icon: "/assets/icons/clay-scorecard.webp",
    screenshot: "/assets/screenshots/yawtzee-best-scorecard.webp",
    screenshotAlt: "Yawtzee: Best Scorecard home screen with new game, history, statistics, rules, and settings actions",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "clay",
    platforms: [],
    actions: []
  },
  {
    id: "mortgage-calculator",
    name: "Mortgage Calculator Suite",
    category: "Real estate",
    description: "Five private real-estate calculators for payments, affordability, VA loans, refinancing, and rentals.",
    icon: "/assets/icons/mortgage-calculator.webp",
    screenshot: "/assets/screenshots/mortgage-calculator.webp",
    screenshotAlt: "Mortgage Calculator Suite home screen with its real-estate estimate tools",
    status: "available",
    statusLabel: "Available now",
    accent: "olive",
    platforms: [{ label: "iPhone & iPad", kind: "ios" }],
    actions: [
      { label: "View on the App Store", href: "https://apps.apple.com/us/app/mortgage-calculator-suite/id6790174039", primary: true }
    ]
  },
  {
    id: "deal-analyzer",
    name: "Deal Analyzer Suite",
    category: "Real estate",
    description: "Evaluate six real-estate strategies with consistent cash-flow, return, financing, and offer metrics.",
    icon: "/assets/icons/deal-analyzer.webp",
    screenshot: "/assets/screenshots/deal-analyzer.webp",
    screenshotAlt: "Deal Analyzer Suite home screen ready to start a new property analysis",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "forest",
    platforms: [],
    actions: []
  },
  {
    id: "dream-journal",
    name: "Dream Journal: AI Analyzer",
    category: "Wellness",
    description: "Capture dreams in a private journal and explore them through thoughtful AI-guided reflection.",
    icon: "/assets/icons/dream-journal.webp",
    screenshot: "/assets/screenshots/dream-journal.webp",
    screenshotAlt: "Dream Journal home screen with a clay moon illustration and journal action",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "lilac",
    platforms: [],
    actions: []
  },
  {
    id: "abc-smash",
    name: "ABC Smash: Letter Adventure",
    category: "Learning",
    description: "A quick, kid-friendly early-literacy game with spoken letter sounds and playful bug-smashing rounds.",
    icon: "/assets/icons/abc-smash.webp",
    screenshot: "/assets/screenshots/abc-smash.webp",
    screenshotAlt: "ABC Smash letter game with a colorful storybook bug in a leafy garden",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "sky",
    platforms: [],
    actions: []
  },
  {
    id: "easy-audio-notes",
    name: "Easy Audio Notes AI",
    category: "Productivity",
    description: "Record live audio or upload a file, then turn it into an organized transcript and useful notes.",
    icon: "/assets/icons/easy-audio-notes.webp",
    screenshot: "/assets/screenshots/easy-audio-notes.webp",
    screenshotAlt: "Easy Audio Notes recording screen with a live timer and waveform",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "coral",
    platforms: [],
    actions: []
  },
  {
    id: "echobeat",
    name: "EchoBeat: Daily Rhythm",
    category: "Daily game",
    description: "Hear the daily beat once, tap it back, and compare your timing with the same challenge as everyone else.",
    icon: "/assets/icons/echobeat.webp",
    screenshot: "/assets/screenshots/echobeat.webp",
    screenshotAlt: "EchoBeat profile screen showing a daily rhythm streak and performance summary",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "violet",
    platforms: [],
    actions: []
  },
  {
    id: "eyes-up",
    name: "Eyes Up: Screen-Free Party",
    category: "Party game",
    description: "Choose a prompt pack, put the phone face-down, and let a screen-free party session run the room.",
    icon: "/assets/icons/eyes-up.webp",
    screenshot: "/assets/screenshots/eyes-up.webp",
    screenshotAlt: "Eyes Up home screen inviting the group to start a screen-free session",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "teal",
    platforms: [],
    actions: []
  },
  {
    id: "hundred",
    name: "Hundred: Daily Point Game",
    category: "Daily game",
    description: "Spend 100 points across five choices revealed one at a time, then see how your final mix turned out.",
    icon: "/assets/icons/hundred.webp",
    screenshot: "/assets/screenshots/hundred.webp",
    screenshotAlt: "Hundred daily game home screen with a 100-point weekend challenge",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "blue",
    platforms: [],
    actions: []
  },
  {
    id: "blackwake-21",
    name: "Blackwake 21",
    category: "Card game",
    description: "Play quick rounds of blackjack against Captain Finn in the storm-lit gaming hold of the Gilded Wake.",
    icon: "/assets/icons/blackwake-21.webp",
    screenshot: "/assets/screenshots/blackwake-21.jpg",
    screenshotAlt: "Blackwake 21 pirate blackjack table with Captain Finn, player cards, totals, and hit and stand actions",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "rose",
    platforms: [],
    actions: []
  },
  {
    id: "pollwar",
    name: "PollWar",
    category: "Social game",
    description: "Create a group poll, invite friends by code or link, play quick games, and turn placement into voting power.",
    icon: "/assets/icons/pollwar.webp",
    screenshot: "/assets/screenshots/pollwar.webp",
    screenshotAlt: "PollWar home screen with quick play, poll creation, room code, and mini-game choices",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "rose",
    platforms: [],
    actions: []
  },
  {
    id: "real-or-ai",
    name: "Real or AI: Daily Challenge",
    category: "Daily game",
    description: "Judge five carefully selected images, reveal what is real or AI-generated, and compare your accuracy.",
    icon: "/assets/icons/real-or-ai.webp",
    screenshot: "/assets/screenshots/real-or-ai.webp",
    screenshotAlt: "Real or AI answer screen revealing an AI-generated modern house image",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "amber",
    platforms: [],
    actions: []
  },
  {
    id: "super-game",
    name: "Super Game: Power Battle",
    category: "Action game",
    description: "A creative party battle where every superpower comes with a twist and every room creates new matchups.",
    icon: "/assets/icons/super-game.webp",
    screenshot: "/assets/screenshots/super-game.webp",
    screenshotAlt: "Super Game home screen with create-lobby and join-lobby actions",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "purple",
    platforms: [],
    actions: []
  },
  {
    id: "dont-touch-red",
    name: "Don’t Touch Red",
    category: "Reflex game",
    description: "Guide a tiny white dot through moving hazards while color tricks, fake alerts, and changing controls try to make you panic.",
    icon: "/assets/icons/dont-touch-red.png",
    screenshot: "/assets/screenshots/dont-touch-red-build-4.png",
    screenshotAlt: "Don’t Touch Red home screen with one Play button, compact navigation, and the red-and-white dot mark",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "red",
    platforms: [],
    actions: []
  },
  {
    id: "one-more",
    name: "One More: Push Your Luck",
    category: "Push-your-luck game",
    description: "Push a score one tap at a time, bank before the risk catches you, then see what would have happened.",
    icon: "/assets/icons/one-more.png",
    screenshot: "/assets/screenshots/one-more-build-7.png",
    screenshotAlt: "One More build 7 game screen starting at zero with a red plus-one button, bust chance, personal best, and verified global best",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "red",
    platforms: [],
    actions: []
  },
  {
    id: "tin-wings",
    name: "Tin Wings",
    category: "Arcade game",
    description: "Fast biplane dogfights with solo survival, online rooms, rockets, ejection, and parachute rescues.",
    icon: "/assets/icons/tin-wings.webp",
    screenshot: "/assets/screenshots/tin-wings.webp",
    screenshotAlt: "Tin Wings clay-style landscape menu with Solo, Online, and Garage actions",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "steel",
    platforms: [],
    actions: []
  }
];
