window.APP_CATALOG = [
  {
    id: "calcspace",
    name: "CalcSpace",
    category: "Everyday utility",
    description: "A focused collection of everyday calculators built for fast answers without the clutter.",
    icon: "/assets/icons/calcspace.png",
    status: "available",
    statusLabel: "Available now",
    accent: "indigo",
    platforms: [{ label: "iPhone & iPad", kind: "ios" }],
    actions: [
      { label: "View on the App Store", href: "https://apps.apple.com/us/app/calcspace/id6789995674", primary: true }
    ]
  },
  {
    id: "mortgage-calculator",
    name: "Mortgage Calculator Suite",
    category: "Real estate",
    description: "Explore payments, affordability, VA loans, refinancing, and rental estimates in one place.",
    icon: "/assets/icons/mortgage-calculator.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "olive",
    platforms: [],
    actions: []
  },
  {
    id: "deal-analyzer",
    name: "Deal Analyzer Suite",
    category: "Real estate",
    description: "Model rentals, flips, BRRRR deals, wholesale offers, and lending scenarios before making the call.",
    icon: "/assets/icons/deal-analyzer.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "forest",
    platforms: [],
    actions: []
  },
  {
    id: "dream-journal",
    name: "Dream Journal: AI Analyzer",
    category: "Wellness",
    description: "Capture dreams, uncover patterns, and revisit thoughtful AI-guided interpretations in a private journal.",
    icon: "/assets/icons/dream-journal.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "lilac",
    platforms: [],
    actions: []
  },
  {
    id: "abc-smash",
    name: "ABC Smash: Letter Adventure",
    category: "Learning",
    description: "A playful letter adventure that turns early reading practice into quick, colorful challenges.",
    icon: "/assets/icons/abc-smash.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "sky",
    platforms: [],
    actions: []
  },
  {
    id: "easy-audio-notes",
    name: "Easy Audio Notes AI",
    category: "Productivity",
    description: "Record a thought and turn it into organized, searchable notes without slowing down your day.",
    icon: "/assets/icons/easy-audio-notes.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "coral",
    platforms: [],
    actions: []
  },
  {
    id: "echobeat",
    name: "EchoBeat: Daily Rhythm",
    category: "Daily game",
    description: "Hear a five-second rhythm once, tap it back, and see how closely your timing matches.",
    icon: "/assets/icons/echobeat.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "violet",
    platforms: [],
    actions: []
  },
  {
    id: "eyes-up",
    name: "Eyes Up: Screen-Free Party",
    category: "Party game",
    description: "A screen-free party host that gets conversations moving while the phone stays face-down.",
    icon: "/assets/icons/eyes-up.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "teal",
    platforms: [],
    actions: []
  },
  {
    id: "hundred",
    name: "Hundred: Daily Point Game",
    category: "Daily game",
    description: "Allocate 100 points across surprise choices, one reveal at a time, and compare your instincts.",
    icon: "/assets/icons/hundred.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "blue",
    platforms: [],
    actions: []
  },
  {
    id: "pollwar",
    name: "PollWar",
    category: "Social game",
    description: "Create fast live polls, rally each side, and let the room decide what wins.",
    icon: "/assets/icons/pollwar.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "rose",
    platforms: [],
    actions: []
  },
  {
    id: "real-or-ai",
    name: "Real or AI: Daily Challenge",
    category: "Daily game",
    description: "Guess whether an image is real or AI-generated in a quick daily visual challenge.",
    icon: "/assets/icons/real-or-ai.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "amber",
    platforms: [],
    actions: []
  },
  {
    id: "super-game",
    name: "Super Game: Power Battle",
    category: "Action game",
    description: "A fast power battle built for quick rounds, bold moves, and big momentum swings.",
    icon: "/assets/icons/super-game.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "purple",
    platforms: [],
    actions: []
  },
  {
    id: "tin-wings",
    name: "Tin Wings",
    category: "Arcade game",
    description: "Arcade biplane dogfights with a tactile tin-toy feel, solo survival, and online battles.",
    icon: "/assets/icons/tin-wings.png",
    status: "coming",
    statusLabel: "Coming soon",
    accent: "steel",
    platforms: [],
    actions: []
  }
];
