#!/bin/sh
set -eu

BASE_URL=${1:-https://italianbrosco.com}
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM

curl -fsSL "$BASE_URL/" -o "$TMP_DIR/home.html"
curl -fsSL "$BASE_URL/catalog.js" -o "$TMP_DIR/catalog.js"
curl -fsSL "$BASE_URL/app.js" -o "$TMP_DIR/app.js"
curl -fsSL "$BASE_URL/app-ads.txt" -o "$TMP_DIR/app-ads.txt"
curl -fsSL "$BASE_URL/assets/favicon.svg" -o "$TMP_DIR/favicon.svg"
curl -fsSL "$BASE_URL/debug/apps/" -o "$TMP_DIR/debug-apps.html"
curl -fsSL "$BASE_URL/abc-smash/privacy/" -o "$TMP_DIR/abc-smash-privacy.html"
curl -fsSL "$BASE_URL/abc-smash/support/" -o "$TMP_DIR/abc-smash-support.html"
curl -fsSL "$BASE_URL/are-you-human/privacy/" -o "$TMP_DIR/are-you-human-privacy.html"
curl -fsSL "$BASE_URL/are-you-human/support/" -o "$TMP_DIR/are-you-human-support.html"
curl -fsSL "$BASE_URL/clay-scorecard/privacy/" -o "$TMP_DIR/clay-privacy.html"
curl -fsSL "$BASE_URL/clay-scorecard/support/" -o "$TMP_DIR/clay-support.html"
curl -fsSL "$BASE_URL/road-trip-arcade/privacy/" -o "$TMP_DIR/road-trip-privacy.html"
curl -fsSL "$BASE_URL/road-trip-arcade/support/" -o "$TMP_DIR/road-trip-support.html"
curl -fsSL "$BASE_URL/tin-wings/privacy/" -o "$TMP_DIR/tin-wings-privacy.html"
curl -fsSL "$BASE_URL/tin-wings/support/" -o "$TMP_DIR/tin-wings-support.html"
curl -fsSL "$BASE_URL/blackwake-21/privacy/" -o "$TMP_DIR/blackwake-21-privacy.html"
curl -fsSL "$BASE_URL/blackwake-21/support/" -o "$TMP_DIR/blackwake-21-support.html"
curl -fsSL "$BASE_URL/dont-touch-red/privacy/" -o "$TMP_DIR/dont-touch-red-privacy.html"
curl -fsSL "$BASE_URL/dont-touch-red/support/" -o "$TMP_DIR/dont-touch-red-support.html"
curl -fsSL "$BASE_URL/dealanalyzer/deal/" -o "$TMP_DIR/deal-viewer.html"
curl -fsSL "$BASE_URL/.well-known/apple-app-site-association" -o "$TMP_DIR/apple-app-site-association"
curl -fsSL "$BASE_URL/.well-known/assetlinks.json" -o "$TMP_DIR/assetlinks.json"

grep -q '<title>Italian Bros — Independent product studio</title>' "$TMP_DIR/home.html"
grep -q 'rel="icon" href="/assets/favicon.svg"' "$TMP_DIR/home.html"
grep -q '<svg' "$TMP_DIR/favicon.svg"
grep -q 'window.APP_CATALOG' "$TMP_DIR/catalog.js"
grep -q 'Release updates coming soon' "$TMP_DIR/app.js"
test "$(wc -l < "$TMP_DIR/app-ads.txt" | tr -d ' ')" -eq 1
grep -qx 'google.com, pub-7421827000635278, DIRECT, f08c47fec0942fa0' "$TMP_DIR/app-ads.txt"
if grep -Eqi 'testflight\.apple\.com|play\.google\.com/apps/testing|public beta|closed test' "$TMP_DIR/home.html" "$TMP_DIR/catalog.js" "$TMP_DIR/app.js"; then
  printf 'Testing links or testing language leaked into the public showcase.\n' >&2
  exit 1
fi
grep -q '<title>Italianbros Co. — Digital Officina</title>' "$TMP_DIR/debug-apps.html"
grep -q '<title>ABC Smash Privacy Policy' "$TMP_DIR/abc-smash-privacy.html"
grep -q 'No third-party analytics or advertising' "$TMP_DIR/abc-smash-privacy.html"
grep -q '<title>ABC Smash Support' "$TMP_DIR/abc-smash-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/abc-smash-support.html"
grep -q '<title>Are You Human? Privacy Policy' "$TMP_DIR/are-you-human-privacy.html"
grep -q 'does not require an account' "$TMP_DIR/are-you-human-privacy.html"
grep -q '<title>Are You Human? Support' "$TMP_DIR/are-you-human-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/are-you-human-support.html"
grep -q '<title>Clay Scorecard Privacy Policy' "$TMP_DIR/clay-privacy.html"
grep -q 'does not collect or transmit personal data' "$TMP_DIR/clay-privacy.html"
grep -q '<title>Clay Scorecard Support' "$TMP_DIR/clay-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/clay-support.html"
grep -q '<title>Road Trip Arcade Privacy Policy' "$TMP_DIR/road-trip-privacy.html"
grep -q 'does not collect or transmit personal data' "$TMP_DIR/road-trip-privacy.html"
grep -q '<title>Road Trip Arcade Support' "$TMP_DIR/road-trip-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/road-trip-support.html"
grep -q '<title>Tin Wings Privacy Policy' "$TMP_DIR/tin-wings-privacy.html"
grep -q 'temporary room and gameplay state' "$TMP_DIR/tin-wings-privacy.html"
grep -q '<title>Tin Wings Support' "$TMP_DIR/tin-wings-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/tin-wings-support.html"
grep -q '<title>Blackwake 21 Privacy Policy' "$TMP_DIR/blackwake-21-privacy.html"
grep -q 'does not collect or transmit personal data' "$TMP_DIR/blackwake-21-privacy.html"
grep -q '<title>Blackwake 21 Support' "$TMP_DIR/blackwake-21-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/blackwake-21-support.html"
grep -q '<title>Don’t Touch Red Privacy Policy' "$TMP_DIR/dont-touch-red-privacy.html"
grep -q 'Google Mobile Ads' "$TMP_DIR/dont-touch-red-privacy.html"
grep -q '<title>Don’t Touch Red Support' "$TMP_DIR/dont-touch-red-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/dont-touch-red-support.html"
grep -q '<title>Shared Deal — Deal Analyzer</title>' "$TMP_DIR/deal-viewer.html"
grep -q 'class="header-title">Shared Deal' "$TMP_DIR/deal-viewer.html"
grep -q 'styles.css?v=20260813.1' "$TMP_DIR/deal-viewer.html"
grep -q 'id="results-heading">RESULTS' "$TMP_DIR/deal-viewer.html"
grep -q '257M5TM5Z8.com.theitalians.dealanalyzer' "$TMP_DIR/apple-app-site-association"
grep -q '"/dealanalyzer/deal/"' "$TMP_DIR/apple-app-site-association"
grep -q '257M5TM5Z8.com.theitalians.mortgagecalculator' "$TMP_DIR/apple-app-site-association"
grep -q '"/mortgagecalc/estimate"' "$TMP_DIR/apple-app-site-association"
grep -q 'com.theitalians.dealanalyzer' "$TMP_DIR/assetlinks.json"
grep -q 'E6:D8:41:08:AD:57:1D:DE:4C:6A:AD:D4:B7:AB:DE:27:57:F0:CB:91:53:81:A3:02:02:C7:3D:B3:22:D8:65:75' "$TMP_DIR/assetlinks.json"
grep -q 'com.theitalians.mortgagecalculator' "$TMP_DIR/assetlinks.json"
grep -q 'D1:0E:59:B1:7F:CD:3F:EA:50:02:D8:84:9E:6A:DB:3A:D3:35:98:AD:3A:70:AC:FD:26:95:28:84:68:D4:B9:49' "$TMP_DIR/assetlinks.json"

for icon in abc-smash blackwake-21 calcspace clay-scorecard deal-analyzer dream-journal easy-audio-notes echobeat eyes-up hundred mortgage-calculator pollwar real-or-ai road-trip-arcade super-game tin-wings; do
  curl -fsSL "$BASE_URL/assets/icons/$icon.webp" -o "$TMP_DIR/$icon.webp"
  test -s "$TMP_DIR/$icon.webp"
done

curl -fsSL "$BASE_URL/assets/icons/are-you-human.png" -o "$TMP_DIR/are-you-human.png"
test -s "$TMP_DIR/are-you-human.png"
curl -fsSL "$BASE_URL/assets/icons/dont-touch-red.png" -o "$TMP_DIR/dont-touch-red.png"
test -s "$TMP_DIR/dont-touch-red.png"
curl -fsSL "$BASE_URL/assets/screenshots/dont-touch-red.png" -o "$TMP_DIR/dont-touch-red-screen.png"
test -s "$TMP_DIR/dont-touch-red-screen.png"
curl -fsSL "$BASE_URL/assets/icons/one-more.png" -o "$TMP_DIR/one-more.png"
test -s "$TMP_DIR/one-more.png"
curl -fsSL "$BASE_URL/assets/screenshots/one-more-build-11.png" -o "$TMP_DIR/one-more-screen.png"
test -s "$TMP_DIR/one-more-screen.png"
grep -q 'id: "one-more"' "$TMP_DIR/catalog.js"
grep -q 'name: "One More: Push Your Luck"' "$TMP_DIR/catalog.js"

printf 'Verified %s: showcase, catalog, 19 icons including One More, existing legal pages, Deal Analyzer universal/app links and shared viewer, and preserved /debug/apps page.\n' "$BASE_URL"
