#!/bin/sh
set -eu

BASE_URL=${1:-https://italianbrosco.com}
ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM

curl -fsSL "$BASE_URL/" -o "$TMP_DIR/home.html"
curl -fsSL "$BASE_URL/catalog.js" -o "$TMP_DIR/catalog.js"
curl -fsSL "$BASE_URL/app.js" -o "$TMP_DIR/app.js"
curl -fsSL "$BASE_URL/styles.css" -o "$TMP_DIR/styles.css"
curl -fsSL "$BASE_URL/app-ads.txt" -o "$TMP_DIR/app-ads.txt"
curl -fsSL "$BASE_URL/assets/favicon.svg" -o "$TMP_DIR/favicon.svg"
curl -fsSL "$BASE_URL/assets/brand/atelier-emblem.svg" -o "$TMP_DIR/atelier-emblem.svg"
curl -fsSL "$BASE_URL/assets/brand/italian-bros-crest.webp" -o "$TMP_DIR/italian-bros-crest.webp"
curl -fsSL "$BASE_URL/assets/brand/italian-bros-support.webp" -o "$TMP_DIR/italian-bros-support.webp"
curl -fsSL "$BASE_URL/assets/brand/italian-bros-crest-transparent.png" -o "$TMP_DIR/italian-bros-crest-transparent.png"
curl -fsSL "$BASE_URL/assets/brand/italian-bros-wordmark.png" -o "$TMP_DIR/italian-bros-wordmark.png"
curl -fsSL "$BASE_URL/assets/brand/italian-bros-support-transparent.png" -o "$TMP_DIR/italian-bros-support-transparent.png"
curl -fsSL "$BASE_URL/assets/icons/mustard-seed-church.png" -o "$TMP_DIR/mustard-seed-church.png"
curl -fsSL "$BASE_URL/assets/screenshots/mustard-seed-church.webp?v=20260825.1" -o "$TMP_DIR/mustard-seed-church.webp"
for screenshot in calcspace mortgage-calculator dream-journal deal-analyzer; do
  curl -fsSL "$BASE_URL/assets/screenshots/$screenshot.webp?v=20260824.1" -o "$TMP_DIR/$screenshot.webp"
done
curl -fsSL "$BASE_URL/debug/apps/" -o "$TMP_DIR/debug-apps.html"
curl -fsSL "$BASE_URL/abc-smash/privacy/" -o "$TMP_DIR/abc-smash-privacy.html"
curl -fsSL "$BASE_URL/abc-smash/support/" -o "$TMP_DIR/abc-smash-support.html"
curl -fsSL "$BASE_URL/are-you-human/privacy/" -o "$TMP_DIR/are-you-human-privacy.html"
curl -fsSL "$BASE_URL/are-you-human/support/" -o "$TMP_DIR/are-you-human-support.html"
curl -fsSL "$BASE_URL/clay-scorecard/privacy/" -o "$TMP_DIR/clay-privacy.html"
curl -fsSL "$BASE_URL/clay-scorecard/support/" -o "$TMP_DIR/clay-support.html"
curl -fsSL "$BASE_URL/road-trip-arcade/privacy/" -o "$TMP_DIR/road-trip-privacy.html"
curl -fsSL "$BASE_URL/road-trip-arcade/support/" -o "$TMP_DIR/road-trip-support.html"
curl -fsSL "$BASE_URL/tin-wings/privacy/" -o "$TMP_DIR/tin-wings-privacy.html"
curl -fsSL "$BASE_URL/tin-wings/support/" -o "$TMP_DIR/tin-wings-support.html"
curl -fsSL "$BASE_URL/blackwake-21/privacy/" -o "$TMP_DIR/blackwake-21-privacy.html"
curl -fsSL "$BASE_URL/blackwake-21/support/" -o "$TMP_DIR/blackwake-21-support.html"
curl -fsSL "$BASE_URL/dont-touch-red/privacy/" -o "$TMP_DIR/dont-touch-red-privacy.html"
curl -fsSL "$BASE_URL/dont-touch-red/support/" -o "$TMP_DIR/dont-touch-red-support.html"
curl -fsSL "$BASE_URL/marbles/privacy/" -o "$TMP_DIR/marbles-privacy.html"
curl -fsSL "$BASE_URL/marbles/support/" -o "$TMP_DIR/marbles-support.html"
curl -fsSL "$BASE_URL/pt-airman/privacy/" -o "$TMP_DIR/pt-airman-privacy.html"
curl -fsSL "$BASE_URL/pt-airman/support/" -o "$TMP_DIR/pt-airman-support.html"
curl -fsSL "$BASE_URL/embrace-the-suck/privacy/" -o "$TMP_DIR/embrace-the-suck-privacy.html"
curl -fsSL "$BASE_URL/embrace-the-suck/support/" -o "$TMP_DIR/embrace-the-suck-support.html"
curl -fsSL "$BASE_URL/one-more/privacy/" -o "$TMP_DIR/one-more-privacy.html"
curl -fsSL "$BASE_URL/ricochet/privacy/" -o "$TMP_DIR/ricochet-privacy.html"
curl -fsSL "$BASE_URL/ricochet/support/" -o "$TMP_DIR/ricochet-support.html"
curl -fsSL "$BASE_URL/draw-your-defense/privacy/" -o "$TMP_DIR/draw-your-defense-privacy.html"
curl -fsSL "$BASE_URL/draw-your-defense/support/" -o "$TMP_DIR/draw-your-defense-support.html"
curl -fsSL "$BASE_URL/dice-and-dice/privacy/" -o "$TMP_DIR/dice-and-dice-privacy.html"
curl -fsSL "$BASE_URL/dice-and-dice/support/" -o "$TMP_DIR/dice-and-dice-support.html"
curl -fsSL "$BASE_URL/one-more/delete-account/" -o "$TMP_DIR/one-more-delete-account.html"
curl -fsSL "$BASE_URL/dealanalyzer/deal/" -o "$TMP_DIR/deal-viewer.html"
curl -fsSL "$BASE_URL/.well-known/apple-app-site-association" -o "$TMP_DIR/apple-app-site-association"
curl -fsSL "$BASE_URL/.well-known/assetlinks.json" -o "$TMP_DIR/assetlinks.json"
curl -fsSL "$BASE_URL/tin-wings/join/?room=M6VU" -o "$TMP_DIR/tin-wings-join.html"
curl -fsSL "$BASE_URL/yawtzee/join/?game=123456" -o "$TMP_DIR/yawtzee-join.html"
curl -fsSL "$BASE_URL/real-or-ai/join/?code=AB23CD" -o "$TMP_DIR/real-or-ai-join.html"
curl -fsSL "$BASE_URL/dont-touch-red/invite/?room=0123456789abcdef" -o "$TMP_DIR/dont-touch-red-invite.html"

grep -q '<title>Italian Bros — Independent product studio</title>' "$TMP_DIR/home.html"
grep -q 'rel="icon" href="/assets/favicon.svg"' "$TMP_DIR/home.html"
grep -q 'styles.css?v=20260824.1' "$TMP_DIR/home.html"
grep -q 'app.js?v=20260825.4' "$TMP_DIR/home.html"
grep -q 'catalog.js?v=20260825.5' "$TMP_DIR/home.html"
grep -q '<strong data-total-count>27</strong>' "$TMP_DIR/home.html"
grep -q 'mailto:italianbrosco@proton.me' "$TMP_DIR/app.js"
grep -q 'Email us at italianbrosco@proton.me' "$TMP_DIR/app.js"
grep -q 'grid-template-columns: repeat(3, minmax(0, 1fr));' "$TMP_DIR/styles.css"
grep -q 'grid-auto-rows: 280px;' "$TMP_DIR/styles.css"
grep -q 'object-fit: contain;' "$TMP_DIR/styles.css"
grep -q 'width: 162px;' "$TMP_DIR/styles.css"
grep -q 'width: 148px;' "$TMP_DIR/styles.css"
grep -q 'width: 136px;' "$TMP_DIR/styles.css"
grep -q 'screenshotVersion: "20260824.1"' "$TMP_DIR/catalog.js"
if grep -q '.phone-preview::before' "$TMP_DIR/styles.css"; then
  printf 'Synthetic phone notch still overlays screenshots in production.\n' >&2
  exit 1
fi
if grep -Eq '\.phone-preview-landscape[^{]*\{[^}]*bottom:[[:space:]]*-' "$TMP_DIR/styles.css"; then
  printf 'A landscape phone preview still uses a clipped negative bottom offset.\n' >&2
  exit 1
fi
grep -q 'bottom: 16px;' "$TMP_DIR/styles.css"
grep -q 'bottom: 22px;' "$TMP_DIR/styles.css"
grep -q 'bottom: 20px;' "$TMP_DIR/styles.css"
if grep -Eq 'Three brothers · one independent studio|Independent<br />apps|apps in our workshop|Direct from our workshop|id="about"|grid-auto-rows: calc\(\(100%' "$TMP_DIR/home.html" "$TMP_DIR/app.js" "$TMP_DIR/styles.css"; then
  printf 'Retired homepage copy, studio section, or overlapping percentage tracks remain in production.\n' >&2
  exit 1
fi
grep -q '<svg' "$TMP_DIR/favicon.svg"
grep -q 'Italian Bros atelier emblem' "$TMP_DIR/atelier-emblem.svg"
cmp -s "$ROOT/assets/brand/italian-bros-crest.webp" "$TMP_DIR/italian-bros-crest.webp"
for screenshot in calcspace mortgage-calculator dream-journal deal-analyzer; do
  cmp -s "$ROOT/assets/screenshots/$screenshot.webp" "$TMP_DIR/$screenshot.webp"
done
cmp -s "$ROOT/assets/brand/italian-bros-support.webp" "$TMP_DIR/italian-bros-support.webp"
cmp -s "$ROOT/assets/brand/italian-bros-crest-transparent.png" "$TMP_DIR/italian-bros-crest-transparent.png"
cmp -s "$ROOT/assets/brand/italian-bros-wordmark.png" "$TMP_DIR/italian-bros-wordmark.png"
cmp -s "$ROOT/assets/brand/italian-bros-support-transparent.png" "$TMP_DIR/italian-bros-support-transparent.png"
cmp -s "$ROOT/assets/icons/mustard-seed-church.png" "$TMP_DIR/mustard-seed-church.png"
cmp -s "$ROOT/assets/screenshots/mustard-seed-church.webp" "$TMP_DIR/mustard-seed-church.webp"
grep -q 'id: "mustard-seed-church"' "$TMP_DIR/catalog.js"
grep -q 'name: "Mustard Seed Church"' "$TMP_DIR/catalog.js"
for retired_asset in three-brothers-fountain.png three-brothers-fountain.webp three-brothers-ink.webp; do
  if curl -fsS -o /dev/null "$BASE_URL/assets/brand/$retired_asset" 2>/dev/null; then
    printf 'Retired three-brothers artwork is still publicly served: %s\n' "$retired_asset" >&2
    exit 1
  fi
done
grep -q 'window.APP_CATALOG' "$TMP_DIR/catalog.js"
grep -q 'Release updates coming soon' "$TMP_DIR/app.js"
test "$(wc -l < "$TMP_DIR/app-ads.txt" | tr -d ' ')" -eq 1
grep -qx 'google.com, pub-7421827000635278, DIRECT, f08c47fec0942fa0' "$TMP_DIR/app-ads.txt"
if grep -Eqi 'testflight\.apple\.com|play\.google\.com/apps/testing|public beta|closed test' "$TMP_DIR/home.html" "$TMP_DIR/catalog.js" "$TMP_DIR/app.js"; then
  printf 'Testing links or testing language leaked into the public showcase.\n' >&2
  exit 1
fi
grep -q '<title>Italianbros Co. — Digital Officina</title>' "$TMP_DIR/debug-apps.html"
grep -q '<title>ABC Smash Privacy Policy' "$TMP_DIR/abc-smash-privacy.html"
grep -q 'No third-party analytics or advertising' "$TMP_DIR/abc-smash-privacy.html"
grep -q '<title>ABC Smash Support' "$TMP_DIR/abc-smash-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/abc-smash-support.html"
grep -q '<title>Are You Human? Privacy Policy' "$TMP_DIR/are-you-human-privacy.html"
grep -q 'does not require an account' "$TMP_DIR/are-you-human-privacy.html"
grep -q '<title>Are You Human? Support' "$TMP_DIR/are-you-human-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/are-you-human-support.html"
grep -q '<title>Yawtzee: Best Scorecard Privacy Policy' "$TMP_DIR/clay-privacy.html"
grep -q 'transmitted to and stored in Google Firebase' "$TMP_DIR/clay-privacy.html"
grep -q '<title>Yawtzee: Best Scorecard Support' "$TMP_DIR/clay-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/clay-support.html"
grep -q '<title>Road Trip Arcade Privacy Policy' "$TMP_DIR/road-trip-privacy.html"
grep -q 'does not collect or transmit personal data' "$TMP_DIR/road-trip-privacy.html"
grep -q '<title>Road Trip Arcade Support' "$TMP_DIR/road-trip-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/road-trip-support.html"
grep -q '<title>Tin Wings Privacy Policy' "$TMP_DIR/tin-wings-privacy.html"
grep -q 'temporary room and gameplay state' "$TMP_DIR/tin-wings-privacy.html"
grep -q 'Google Mobile Ads' "$TMP_DIR/tin-wings-privacy.html"
grep -q 'coins, unlocked planes and pilots' "$TMP_DIR/tin-wings-privacy.html"
grep -q '<title>Tin Wings Support' "$TMP_DIR/tin-wings-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/tin-wings-support.html"
grep -q '<title>Blackwake 21 Privacy Policy' "$TMP_DIR/blackwake-21-privacy.html"
grep -q 'does not collect or transmit personal data' "$TMP_DIR/blackwake-21-privacy.html"
grep -q '<title>Blackwake 21 Support' "$TMP_DIR/blackwake-21-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/blackwake-21-support.html"
grep -q '<title>Don’t Touch Red Privacy Policy' "$TMP_DIR/dont-touch-red-privacy.html"
grep -q 'Google Mobile Ads' "$TMP_DIR/dont-touch-red-privacy.html"
grep -q '<title>Don’t Touch Red Support' "$TMP_DIR/dont-touch-red-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/dont-touch-red-support.html"
grep -q '<title>Marbles Privacy Policy' "$TMP_DIR/marbles-privacy.html"
grep -q 'does not collect personal information' "$TMP_DIR/marbles-privacy.html"
grep -q '<title>Marbles Support' "$TMP_DIR/marbles-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/marbles-support.html"
grep -q '<title>PT Airman Privacy Policy' "$TMP_DIR/pt-airman-privacy.html"
grep -q 'does not collect, transmit, sell, or share personal data' "$TMP_DIR/pt-airman-privacy.html"
grep -q '<title>PT Airman Support' "$TMP_DIR/pt-airman-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/pt-airman-support.html"
grep -q '<title>Embrace the Suck Privacy Policy' "$TMP_DIR/embrace-the-suck-privacy.html"
grep -q 'does not collect or transmit personal data' "$TMP_DIR/embrace-the-suck-privacy.html"
grep -q '<title>Embrace the Suck Support' "$TMP_DIR/embrace-the-suck-support.html"
grep -q 'sample, local-only activity' "$TMP_DIR/embrace-the-suck-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/embrace-the-suck-support.html"
grep -q '<title>Shared Deal — Deal Analyzer</title>' "$TMP_DIR/deal-viewer.html"
grep -q 'class="header-title">Shared Deal' "$TMP_DIR/deal-viewer.html"
grep -q 'styles.css?v=20260821.1' "$TMP_DIR/deal-viewer.html"
grep -q 'id="results-heading">RESULTS' "$TMP_DIR/deal-viewer.html"
grep -q '257M5TM5Z8.com.theitalians.dealanalyzer' "$TMP_DIR/apple-app-site-association"
grep -q '"/dealanalyzer/deal/"' "$TMP_DIR/apple-app-site-association"
grep -q '257M5TM5Z8.com.theitalians.mortgagecalculator' "$TMP_DIR/apple-app-site-association"
grep -q '"/mortgagecalc/estimate"' "$TMP_DIR/apple-app-site-association"
grep -q 'com.theitalians.dealanalyzer' "$TMP_DIR/assetlinks.json"
grep -q 'E6:D8:41:08:AD:57:1D:DE:4C:6A:AD:D4:B7:AB:DE:27:57:F0:CB:91:53:81:A3:02:02:C7:3D:B3:22:D8:65:75' "$TMP_DIR/assetlinks.json"
grep -q 'com.theitalians.mortgagecalculator' "$TMP_DIR/assetlinks.json"
grep -q 'D1:0E:59:B1:7F:CD:3F:EA:50:02:D8:84:9E:6A:DB:3A:D3:35:98:AD:3A:70:AC:FD:26:95:28:84:68:D4:B9:49' "$TMP_DIR/assetlinks.json"
grep -q '257M5TM5Z8.com.italianbros.clayscorecard' "$TMP_DIR/apple-app-site-association"
grep -q '"/yawtzee/join"' "$TMP_DIR/apple-app-site-association"
grep -q 'com.italianbros.clayscorecard' "$TMP_DIR/assetlinks.json"
grep -q '20:F0:69:44:3B:69:5B:03:4B:02:13:98:97:E8:84:05:CA:5D:C9:34:07:61:FA:1E:DA:6D:F8:EE:30:5C:A7:C0' "$TMP_DIR/assetlinks.json"
grep -q 'Join this scorecard' "$TMP_DIR/yawtzee-join.html"
grep -q "URLSearchParams(location.search).get('game')" "$TMP_DIR/yawtzee-join.html"
grep -q '257M5TM5Z8.com.italianbros.realorai' "$TMP_DIR/apple-app-site-association"
grep -q '"/real-or-ai/join"' "$TMP_DIR/apple-app-site-association"
grep -q 'Join this match' "$TMP_DIR/real-or-ai-join.html"
grep -q "URLSearchParams(location.search).get('code')" "$TMP_DIR/real-or-ai-join.html"
grep -q "realorai://join?code=" "$TMP_DIR/real-or-ai-join.html"
grep -q '257M5TM5Z8.com.julesdavid8.tinwings' "$TMP_DIR/apple-app-site-association"
grep -q '"/tin-wings/join"' "$TMP_DIR/apple-app-site-association"
grep -q '<title>Join a Tin Wings Flight</title>' "$TMP_DIR/tin-wings-join.html"
grep -q "URLSearchParams(location.search).get('room')" "$TMP_DIR/tin-wings-join.html"
grep -q "tinwings://join/" "$TMP_DIR/tin-wings-join.html"
grep -q 'Join this co-op game' "$TMP_DIR/dont-touch-red-invite.html"
grep -q "URLSearchParams(location.search).get('room')" "$TMP_DIR/dont-touch-red-invite.html"
grep -q "donttouchred://coop/" "$TMP_DIR/dont-touch-red-invite.html"

for icon in abc-smash blackwake-21 calcspace clay-scorecard deal-analyzer dream-journal easy-audio-notes echobeat eyes-up hundred marbles mortgage-calculator pollwar pt-airman real-or-ai road-trip-arcade super-game tin-wings; do
  curl -fsSL "$BASE_URL/assets/icons/$icon.webp" -o "$TMP_DIR/$icon.webp"
  test -s "$TMP_DIR/$icon.webp"
done

curl -fsSL "$BASE_URL/assets/icons/embrace-the-suck.webp" -o "$TMP_DIR/embrace-the-suck.webp"
test -s "$TMP_DIR/embrace-the-suck.webp"
curl -fsSL "$BASE_URL/assets/screenshots/embrace-the-suck.webp" -o "$TMP_DIR/embrace-the-suck-screen.webp"
test -s "$TMP_DIR/embrace-the-suck-screen.webp"
grep -q 'id: "embrace-the-suck"' "$TMP_DIR/catalog.js"
grep -q 'name: "Embrace the Suck!"' "$TMP_DIR/catalog.js"

curl -fsSL "$BASE_URL/assets/icons/are-you-human.png" -o "$TMP_DIR/are-you-human.png"
test -s "$TMP_DIR/are-you-human.png"
curl -fsSL "$BASE_URL/assets/icons/dont-touch-red.png" -o "$TMP_DIR/dont-touch-red.png"
test -s "$TMP_DIR/dont-touch-red.png"
curl -fsSL "$BASE_URL/assets/screenshots/dont-touch-red.png" -o "$TMP_DIR/dont-touch-red-screen.png"
test -s "$TMP_DIR/dont-touch-red-screen.png"
curl -fsSL "$BASE_URL/assets/icons/one-more.png" -o "$TMP_DIR/one-more.png"
test -s "$TMP_DIR/one-more.png"
curl -fsSL "$BASE_URL/assets/screenshots/one-more-build-11.png" -o "$TMP_DIR/one-more-screen.png"
test -s "$TMP_DIR/one-more-screen.png"
grep -q 'id: "one-more"' "$TMP_DIR/catalog.js"
grep -q 'name: "One More: Push Your Luck"' "$TMP_DIR/catalog.js"
grep -q '<title>One More Privacy Policy — Italian Bros</title>' "$TMP_DIR/one-more-privacy.html"
grep -q 'Google rewarded ad' "$TMP_DIR/one-more-privacy.html"
grep -q 'hashed version of your password' "$TMP_DIR/one-more-privacy.html"
grep -q '<title>Delete One More Account — Italian Bros</title>' "$TMP_DIR/one-more-delete-account.html"
grep -q '/api/one-more/account/delete' "$TMP_DIR/one-more-delete-account.html"
grep -q 'One More account deletion page' "$TMP_DIR/one-more-privacy.html"
curl -fsSL "$BASE_URL/assets/icons/ricochet.webp" -o "$TMP_DIR/ricochet.webp"
test -s "$TMP_DIR/ricochet.webp"
curl -fsSL "$BASE_URL/assets/screenshots/ricochet.webp" -o "$TMP_DIR/ricochet-screen.webp"
test -s "$TMP_DIR/ricochet-screen.webp"
grep -q 'id: "ricochet"' "$TMP_DIR/catalog.js"
grep -q 'name: "Ricochet!"' "$TMP_DIR/catalog.js"
grep -q '<title>Ricochet! Privacy Policy — Italian Bros</title>' "$TMP_DIR/ricochet-privacy.html"
grep -q 'does not collect, sell, or share personal data' "$TMP_DIR/ricochet-privacy.html"
grep -q '<title>Ricochet! Support — Italian Bros</title>' "$TMP_DIR/ricochet-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/ricochet-support.html"
curl -fsSL "$BASE_URL/assets/icons/draw-your-defense.webp" -o "$TMP_DIR/draw-your-defense.webp"
test -s "$TMP_DIR/draw-your-defense.webp"
curl -fsSL "$BASE_URL/assets/screenshots/draw-your-defense.webp" -o "$TMP_DIR/draw-your-defense-screen.webp"
test -s "$TMP_DIR/draw-your-defense-screen.webp"
grep -q 'id: "draw-your-defense"' "$TMP_DIR/catalog.js"
grep -q 'name: "Draw Your Defense"' "$TMP_DIR/catalog.js"
grep -q '<title>Draw Your Defense Privacy Policy — Italian Bros</title>' "$TMP_DIR/draw-your-defense-privacy.html"
grep -q 'does not collect, transmit, sell, or share personal data' "$TMP_DIR/draw-your-defense-privacy.html"
grep -q '<title>Draw Your Defense Support — Italian Bros</title>' "$TMP_DIR/draw-your-defense-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/draw-your-defense-support.html"
curl -fsSL "$BASE_URL/assets/icons/dice-and-dice.webp" -o "$TMP_DIR/dice-and-dice.webp"
test -s "$TMP_DIR/dice-and-dice.webp"
curl -fsSL "$BASE_URL/assets/screenshots/dice-and-dice.webp" -o "$TMP_DIR/dice-and-dice-screen.webp"
test -s "$TMP_DIR/dice-and-dice-screen.webp"
grep -q 'id: "dice-and-dice"' "$TMP_DIR/catalog.js"
grep -q 'name: "Dice & Dice: Best Dice"' "$TMP_DIR/catalog.js"
grep -q '<title>Dice &amp; Dice: Best Dice Privacy Policy — Italian Bros</title>' "$TMP_DIR/dice-and-dice-privacy.html"
grep -q 'does not collect, transmit, sell, or share personal data' "$TMP_DIR/dice-and-dice-privacy.html"
grep -q '<title>Dice &amp; Dice: Best Dice Support — Italian Bros</title>' "$TMP_DIR/dice-and-dice-support.html"
grep -q 'ciminillo@italianbrosco.com' "$TMP_DIR/dice-and-dice-support.html"
curl -fsSL "$BASE_URL/assets/icons/get-in-line.png" -o "$TMP_DIR/get-in-line.png"
test -s "$TMP_DIR/get-in-line.png"
curl -fsSL "$BASE_URL/assets/screenshots/get-in-line-build-7.png" -o "$TMP_DIR/get-in-line-screen.png"
test -s "$TMP_DIR/get-in-line-screen.png"
grep -q 'id: "get-in-line"' "$TMP_DIR/catalog.js"
grep -q 'name: "Get In Line: Rank & Reveal"' "$TMP_DIR/catalog.js"

node "$ROOT/scripts/verify-food-glorious-food-demo.mjs" "$BASE_URL"

printf 'Verified %s: showcase, Food Glorious Food demo, 27-app catalog including Mustard Seed Church, live legal pages, Deal Analyzer and Yawtzee universal/app links, and preserved /debug/apps page.\n' "$BASE_URL"
